# Generated by Django 2.0 on 2018-03-29 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publics',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
