# Generated by Django 2.0 on 2018-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0003_auto_20180402_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='publics',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
